const config = {
    username: '<Language Understanding API username here>',
    password: '<Language Understanding API password here>',
    url : 'https://gateway.watsonplatform.net/natural-language-understanding/api',
    accname: '<Account to use for trailing here>',
    posting: '<Posting key of the account>',
    following: [
        {
            account: 'ocd',
            check_context: true,
            weight_divider: 0.05,
            max_weight: 5000,
            comment: `#### Hi @{AUTHOR}!\n\nYour post was upvoted by utopian.io in cooperation with {VOTER} - supporting knowledge, innovation and technological advancement on the Steem Blockchain.\n\n#### Contribute to Open Source with utopian.io\nLearn how to contribute on <a href="https://join.utopian.io">our website</a> and join the new open source economy.\n\n**Want to chat? Join the Utopian Community on Discord https://discord.gg/h52nFrV**`
        },
        {
            account: 'steemstem',
            check_context: false,
            weight_divider: 0.15,
            max_weight: 15000,
            comment: `#### Hi @{AUTHOR}!\n\nYour post was upvoted by utopian.io in cooperation with {VOTER} - supporting knowledge, innovation and technological advancement on the Steem Blockchain.\n\n#### Contribute to Open Source with utopian.io\nLearn how to contribute on <a href="https://join.utopian.io">our website</a> and join the new open source economy.\n\n**Want to chat? Join the Utopian Community on Discord https://discord.gg/h52nFrV**`
        },
        {
            account: 'steemmakers',
            check_context: true,
            weight_divider: 0.05,
            max_weight: 5000,
            comment: `#### Hi @{AUTHOR}!\n\nYour post was upvoted by utopian.io in cooperation with {VOTER} - supporting knowledge, innovation and technological advancement on the Steem Blockchain.\n\n#### Contribute to Open Source with utopian.io\nLearn how to contribute on <a href="https://join.utopian.io">our website</a> and join the new open source economy.\n\n**Want to chat? Join the Utopian Community on Discord https://discord.gg/h52nFrV**`
        },
        {
            account: 'steemhunt',
            check_context: true,
            weight_divider: 0.05,
            max_weight: 5000,
            comment: `#### Hi @{AUTHOR}!\n\nYour post was upvoted by utopian.io in cooperation with {VOTER} - supporting knowledge, innovation and technological advancement on the Steem Blockchain.\n\n#### Contribute to Open Source with utopian.io\nLearn how to contribute on <a href="https://join.utopian.io">our website</a> and join the new open source economy.\n\n**Want to chat? Join the Utopian Community on Discord https://discord.gg/h52nFrV**`
        }
    ],
    labels: [
        '/science/biology/biotechnology',
        '/science/biology/botany',
        '/science/biology/breeding',
        '/science/biology/cytology',
        '/science/biology/marine biology',
        '/science/biology/molecular biology',
        '/science/biology/zoology/endangered species',
        '/science/biology/zoology/entomology',
        '/science/biology/zoology/ornithology',
        '/science/biology/zoology',
        '/science/chemistry/organic chemistry',
        '/science/chemistry',
        '/science/computer science/artificial intelligence',
        '/science/computer science/cryptography',
        '/science/computer science/distributed systems',
        '/science/computer science/information science',
        '/science/computer science/software engineering',
        '/science/computer science',
        '/science/ecology/environmental disaster',
        '/science/ecology/pollution',
        '/science/ecology/waste management/recycling',
        '/science/ecology/waste management/waste disposal',
        '/science/ecology',
        '/science/engineering',
        '/science/geography/cartography',
        '/science/geography/topography',
        '/science/geography',
        '/science/geology/mineralogy',
        '/science/geology/seismology/earthquakes',
        '/science/geology/volcanology/volcanic eruptions',
        '/science/geology',
        '/science/mathematics/algebra',
        '/science/mathematics/arithmetic',
        '/science/mathematics/geometry',
        '/science/mathematics/statistics',
        '/science/mathematics',
        '/science/medicine/cardiology',
        '/science/medicine/dermatology',
        '/science/medicine/embryology',
        '/science/medicine/genetics',
        '/science/medicine/immunology',
        '/science/medicine/medical research',
        '/science/medicine/oncology',
        '/science/medicine/orthopedics',
        '/science/medicine/pediatrics',
        '/science/medicine/pharmacology',
        '/science/medicine/physiology',
        '/science/medicine/psychology and psychiatry/psychoanalysis',
        '/science/medicine/psychology and psychiatry',
        '/science/medicine/surgery/cosmetic surgery',
        '/science/medicine/surgery/transplants',
        '/science/medicine/surgery',
        '/science/medicine/veterinary medicine',
        '/science/medicine',
        '/science/physics/atomic physics',
        '/science/physics/astrophysics',
        '/science/physics/electromagnetism',
        '/science/physics/hydraulics',
        '/science/physics/nanotechnology',
        '/science/physics/optics',
        '/science/physics/space and astronomy',
        '/science/physics/thermodynamics',
        '/science/physics',
        '/business and industrial/aerospace and defense/space technology',
        '/business and industrial/automation/robotics',
        '/business and industrial/business software',
        '/business and industrial/energy/electricity',
        '/hobbies and interests/inventors and patents',
        '/science',
        '/technology and computing/computer security/antivirus and malware',
        '/technology and computing/computer security/network security',
        '/technology and computing/computer security',
        '/technology and computing/data centers',
        '/technology and computing/electronic components',
        '/technology and computing/enterprise technology/data management',
        '/technology and computing/enterprise technology/enterprise resource planning',
        '/technology and computing/hardware/computer/servers',
        '/technology and computing/hardware/computer components/chips and processors',
        '/technology and computing/hardware/computer/components/disks',
        '/technology and computing/hardware/computer/components/graphics cards',
        '/technology and computing/hardware/computer/components/memory/portable',
        '/technology and computing/hardware/computer/components/memory',
        '/technology and computing/hardware/computer/components/motherboards',
        '/technology and computing/hardware/computer/networking/wireless technology',
        '/technology and computing/hardware',
        '/technology and computing/internet technology/isps',
        '/technology and computing/internet technology/social network',
        '/technology and computing/internet technology/web design and html',
        '/technology and computing/internet technology/web search/people search',
        '/technology and computing/internet technology/web search',
        '/technology and computing/internet technology',
        '/technology and computing/networking/network monitoring and management',
        '/technology and computing/networking/vpn and remote access',
        '/technology and computing/networking',
        '/technology and computing/operating systems/linux',
        '/technology and computing/operating systems/mac os',
        '/technology and computing/operating systems/unix',
        '/technology and computing/operating systems/windows',
        '/technology and computing/operating systems',
        '/technology and computing/programming languages/c and c++',
        '/technology and computing/programming languages/java',
        '/technology and computing/programming languages/javascript',
        '/technology and computing/programming languages/visual basic',
        '/technology and computing/programming languages',
        '/technology and computing/software/databases',
        '/technology and computing/software/desktop publishing',
        '/technology and computing/software/desktop video',
        '/technology and computing/software/graphics software/animation',
        '/technology and computing/software/graphics software',
        '/technology and computing/software/net conferencing',
        '/technology and computing/software/shareware and freeware',
        '/technology and computing/technological innovation'
    ]
}

module.exports = config
